= metanorma-plugin-lutaml

image:https://github.com/metanorma/metanorma-plugin-lutaml/workflows/rake/badge.svg["Build Status", link="https://github.com/metanorma/metanorma-plugin-lutaml/actions?workflow=rake"]

== Functionality

Metanorma plugin that allows you to access lutaml objects from a Metanorma document

=== Installation

[source,console]
----
$ gem install metanorma-plugin-lutaml
----

=== Usage, `lutaml` macro

Given `example.exp` file with the content:

[source,exp]
----
SCHEMA test_schema 'test';

(* Need select elements for measure_value *)
 REFERENCE FROM measure_schema
   (measure_value);

  TYPE my_type1 = EXTENSIBLE SELECT;
  END_TYPE;

  TYPE my_type2 = EXTENSIBLE ENUMERATION;
  END_TYPE;

  TYPE my_type3 = EXTENSIBLE ENUMERATION;
  END_TYPE;

  TYPE my_type4 = EXTENSIBLE ENUMERATION;
  END_TYPE;

  TYPE my_type5 = EXTENSIBLE ENUMERATION;
  END_TYPE;
END_SCHEMA;
----

And the `lutaml` macro block:

[source,adoc]
-----
[lutaml,example.exp,my_context]
----

== {{schema.id}}

{% for entity in schema.entities %}
=== {{entity.id}}
{% endfor %}

----
-----

Where:

* content within the block is called the "`template`";

* `{example.exp}` is the location of the exp schema file that contains data to be loaded. Location of the file is computed relative to the source directory that `[lutaml]` is used (e.g., if `[lutaml,example.exp,my_context]` is invoked in an `.adoc` file located at `/foo/bar/doc.adoc`, the data file is expected to be found at `/foo/bar/example.exp`);

* `{my_context}` is the name where the EXPRESS Repository read from the .exp file can be accessed with. Context object is a serialized  https://github.com/lutaml/expressir/blob/master/lib/expressir/model/schema.rb[Expressir::Model::Schema] object with all variable names available. See https://github.com/lutaml/expressir[Expressir] docs for reference.

Will produce this output:

[source,adoc]
-----
== test_schema

=== my_type1
=== my_type2
=== my_type3
=== my_type4
=== my_type5
-----

This macro also supports `.lutaml` files.

Instead of using the direct path to the file one can use `lutaml-express-index` document attribute to supply directory with express files or yaml index file to parse as well as the cache file location. The syntax is as follows:

[source,adoc]
-----
:lutaml-express-index: my_custom_name; dir_or_index_path[; cache=cache_path]
-----

Where:

* `my_custom_name` - is name of the parsed express files context for the later use with lutaml macro

* `dir_or_index_path` - location of directory with express files or path to yaml index file to parse

* `cache_path` - optional, location of the expressir cache file to use

Example of real usage:

[source,adoc]
-----
= Document title
Author
:lutaml-express-index: my_custom_name; /path/to/express_files; cache=/path/to/cache_file.yaml

[lutaml,my_custom_name,my_context]
----
== {{schema.id}}
----
-----


=== Usage, `lutaml_uml_attributes_table` macro

This macro allows to quickly render datamodel attributes/values tables. Given `example.lutaml` file with the content:

[source,java]
----
diagram MyView {
  title "my diagram"

  enum AddressClassProfile {
    imlicistAttributeProfile: CharacterString [0..1] {
      definition
        this is multiline with `ascidoc`
      end definition
    }
  }

  class AttributeProfile {
    +addressClassProfile: CharacterString [0..1]
    imlicistAttributeProfile: CharacterString [0..1] {
      definition this is attribute definition
    }
  }
}
----

And the `lutaml_uml_attributes_table` macro:

[source,adoc]
-----
[lutaml_uml_attributes_table, example.lutaml, AttributeProfile]
-----

Will produce this output:

[source,adoc]
-----
=== AttributeProfile


.AttributeProfile attributes
|===
|Name |Definition |Mandatory/ Optional/ Conditional |Max Occur |Data Type

|addressClassProfile |TODO: enum 's definition |M |1 | `CharacterString`

|imlicistAttributeProfile |this is attribute definition with multiply lines |M |1 | `CharacterString`

|===
-----

In case of "enumeration"(AddressClassProfile) entity:

[source,adoc]
-----
[lutaml_uml_attributes_table, example.lutaml, AddressClassProfile]
-----

Will produce this output:

[source,adoc]
-----
=== AddressClassProfile


.AddressClassProfile values
|===
|Name |Definition

|imlicistAttributeProfile |this is multiline with `ascidoc`

|===
-----

== Documentation

See https://www.metanorma.com.
