
== Usage with LutaML GML Dictionary

=== Rendering a LutaML GML Dictionary: `lutaml_gml_dictionary`

This command allows to render a LutaML GML Dictionary by using Liquid Drop.

GmlDictionaryDrop has the following attributes:

* name
* file_name
* dictionary_entry

Each `dictionary_entry` has the following attributes:

* name
* description

[source,adoc]
----
lutaml_gml_dictionary::/path/to/dictionary.xml[template="/path/to/template.liquid",context=dict]
----

The command accepts the options listed below:

* `/path/to/dictionary.xml` specifies the path of xml file of the
GML Dictionary.

* `template="/path/to/template.liquid"` specifies the liquid template.
  For example, you can create a liquid template and link it by `template`.

* `context=dict` define the context in the template.

[source,adoc]
----
[cols="3a,22a"]
|===
| Name | {{ dict.file_name }}

h| Code h| Description
{% for entry in dict.dictionary_entry %}
| {{ entry.name }} | {{ entry.description }}
{% endfor %}
|===

[.source]
<<source_link>>
----

In spite of specifying the path of the template, you can also define an inline
template within a block by
`[lutaml_gml_dictionary,"/path/to/dictionary.xml",context=dict]`.

[source,adoc]
----
[lutaml_gml_dictionary,"/path/to/dictionary.xml",context=dict]
--
{% capture link %}https://www.test.com/{{ dict.file_name }}{% endcapture %}

[cols="3a,22a"]
|===
| File Name | {{ dict.file_name }}
h| URL | {{ link }}
h| Help | Description
{% for entry in dict.dictionary_entry %}
| {{ entry.name }} | {{ entry.description }}
{% endfor %}
|===

[.source]
<<source_link>>
--
----
